# Generated by Django 4.1.3 on 2023-06-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(default='example@unal.edu.co', max_length=50),
            preserve_default=False,
        ),
    ]
