# Generated by Django 4.1.3 on 2022-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
